# -*- coding: utf-8 -*-
"""conversation table.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13eXAWl3SpJbNUjoNWPNuvF9Vqbqve8FJ
"""

print('F C')
C = 0
while C <= 250:
  F = 9 * C / 5 + 32
  print(F, C)
  C += 10

print('F C')
C = 0
while C <= 250:
  F = 9 * C / 5 + 32
  print('%4.0f %4.0f' % (F, C))
  C += 10

print(' F C')
for C in range(0, 250, 10):
  F = 9 * C / 5 + 32
  print('%4.0f %4.0f' % (F, C))

print(' F C')
for C in range(-50, 50, 5):
  F = 9 * C / 5 + 32
  print('%4.0f %4.0f' % (F, C))

Cs = [0, 10] # create list using []
Cs.append(20) # modify by appending an entry
Cs

Cs = (0, 10) # create a tuple using ()

Cs = [] # empty list
Fs = []
for C in range(0, 250, 25):
  Cs.append(C)
  Fs.append(9 * C / 5 + 32)

print(Cs)

print(Fs)

print(' F C')
for C, F in zip(Cs, Fs):
  print('%4.0f %4.0f' % (F, C))

Fs = [9 * C / 5 + 32 for C in Cs]