# -*- coding: utf-8 -*-
"""sum_up_integer_powers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10d60E5HlRoVzH5uGeCgfsQjgAsnBSh-F
"""

def sum_of_integer_powers(power, end, start = 1):
  return sum([(i) ** power for i in range(start, end+1)])
#defining function to find summation for the i th powers of 1 to a number

power =int(input("enter the power: "))
print("the power is: ", power)
print()
end= int(input("enter the end point for your summation: " ))
print("the end point for your summation is: ", end)

sum_of_integer_powers(power,end)